site_name: COTI
site_url: https://docs.coti.mx/
theme: material
docs_dir: source
site_dir: docs
plugins:
  - glightbox
nav:
  - Inicio:
    - Documentación de COTI: index.md
  - Primeros Pasos:
    - Registro: primeros-pasos/registro.md
    - Modificar Empresa: primeros-pasos/modificar-empresa.md
    - Sucursales: primeros-pasos/sucursal.md
    - Cambiar tu moneda: primeros-pasos/moneda.md
    - Agregar Impuestos: primeros-pasos/impuestos.md
  - Guías paso a paso:
    - Agregar usuario: guias/agregar-usuario.md
  - Configuraciones:
    - personalizar PDF : configuracion/personalizar-pdf.md
  - Como funciona: 
    - Las suscripciones: como-funcionan/las-suscripciones.md
  - Ayuda / Contacto: contacto.md
